/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "app.h"
#define QUANTA 	10

//uint32_t count0;

//typedef enum {
//	MODEM_OFF=0,
//	MODEM_ON,
//	MODEM_READY,
//	MODEM_IDLE,
//}modem_state_t;


//modem_state_t Modem_State = MODEM_OFF;

void Vending_Machine_App_Thread( void )
{
	while(1)
	{
		Vending_Machine_ModemHandler();
		Vending_Machine_State_Ctrl();
	}
}

int main(void)
{
	Vending_Machine_System_Init();
	ATCMD_A7672_Urc_Queue_Init();
	ATCMD_Core_Init();
	osKernelAddThread( Vending_Machine_App_Thread, 3);
	int8_t ret = osKernelLaunch(QUANTA);
	if( ret == -1)
	{
		while(1);
		/*The Scheduler Launch Failed*/
	}

	for(;;);
}
